import Head from 'next/head'
import Image from 'next/image'

import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Generate a Character</h1>

        <div className={styles.grid}>
          <Link href="cultures/bardings">
            <a className={styles.card}>
              <h2>Barding</h2>
            </a>
          </Link>
          <Link href="cultures/dwarves">
            <a className={styles.card}>
              <h2>Dwarves</h2>
            </a>
          </Link>
          <Link href="cultures/elves">
            <a className={styles.card}>
              <h2>Elves</h2>
            </a>
          </Link>
          <Link href="cultures/hobbits">
            <a className={styles.card}>
              <h2>Hobbits</h2>
            </a>
          </Link>
          <Link href="cultures/men_of_bree">
            <a className={styles.card}>
              <h2>Men of Bree</h2>
            </a>
          </Link>
          <Link href="cultures/rangers">
            <a className={styles.card}>
              <h2>Rangers</h2>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
